title: Dataset on Measures of Disagreement over Expected Inflation
description: Download the dataset and view figures using it
baseurl: "/test_disagreement_ricardo" 
url: "https://s-mahdihosseini.github.io"
github_username: s-mahdihosseini

theme: jekyll-theme-cayman
